Revert to latest tag instead of v0.7
sustainable-computing-io/kepler-model-server pull request #283
Opened 2024-07-06 01:17 UTC by KaiyiLiu1234

Reverting to latest tag resolves python3.10 missing error.

2024-07-06 01:21 UTC, sunya-ch commented on model_training/custom-cluster/kind/local-registry.yml
> +---
Is this config file in use by this repo?

2024-07-06 01:21 UTC, sunya-ch approved these changes
Tekton image version change looks good to me.

2024-07-08 01:55 UTC, sthaha requested changes
Looks good overall, but requesting change only to ensure that  if  `[cluster/kind/local-registry.yml](https://github.com/sustainable-computing-io/kepler-model-server/pull/283/files#diff-ec25f9e92cb139bda90bebf5f93d9c3e39cf2a13ba4985010ad7ef32117c2b51)` is not checked in by mistake.

2024-07-10 02:27 UTC, sthaha approved these changes

2024-07-10 02:28 UTC, merged