chore: yamllint all the things
sustainable-computing-io/kepler-model-server pull request #300
Opened 2024-07-10 11:01 UTC by dave-tucker

This adds the same yamllint config that we use in Kepler and adds a Github Workflow to ensure checked in YAML has been correctly linted. Also fixes some minor syntax issues with the GitHub Templates.

2024-07-16 01:41 UTC, sunya-ch commented
Could you please check prometheus-k8s yaml due to the error in this line `The Role "prometheus-k8s" is invalid: rules[0].apiGroups: Required value: resource rules must supply at least one api group`?

2024-07-18 23:43 UTC, sthaha requested changes

2024-07-18 23:43 UTC, sthaha commented on .github/workflows/build-push.yml
> +          platforms: llinux/amd64
typo @dave-tucker

2024-07-18 23:43 UTC, sthaha commented on .vscode/settings.json
> +}
How about we delete this file and ignore it? 
Also contains `Users/dave`...

2024-07-18 23:43 UTC, sthaha commented on manifests/server/kustomization.yaml
> +      fieldpath: metadata.namespace }
`}` added at the end

2024-07-18 23:43 UTC, sthaha commented on manifests/server/kustomization.yaml
> +      fieldpath: spec.template.spec.containers[0].ports[0].containerPort
Wonder how this even worked earlier 🤔

2024-07-18 23:43 UTC, sthaha commented on manifests/server/online-train/patch-trainer.yaml
> +          args: [-u, src/train/online_trainer.py]
could you please verify if this change in indentation (scope) does not break anything?

2024-07-18 23:43 UTC, sthaha commented on manifests/test/model-request-client.yaml
> +            ]
```suggestion
          args:
            - -c,
            - python3.10 -u tests/weight_model_request_test.py && echo Done && sleep infinity
```

2024-09-03 02:30 UTC, sunya-ch commented
Is this duplicated with https://github.com/sustainable-computing-io/kepler-model-server/pull/429?

2024-11-25 11:16 UTC, closed without merging