bump up kepler-action to 0.0.8
sustainable-computing-io/kepler-model-server pull request #313
Opened 2024-07-21 03:34 UTC by SamYuan1990

2024-07-21 04:06 UTC, SamYuan1990 commented
@sunya-ch , I have not get the point https://github.com/sustainable-computing-io/local-dev-cluster/blob/main/main.sh#L93 what's the reason for mkdir -p report an error...

2024-07-22 01:42 UTC, sthaha commented on model_training/script.sh
> +export KUBECONFIG=${KUBECONFIG:"/tmp/kubeconfig"}
```suggestion
export KUBECONFIG=${KUBECONFIG:-"/tmp/kubeconfig"}
```

2024-07-22 01:42 UTC, sthaha commented on model_training/script.sh
>  export ENTRYPOINT_IMG=${ENTRYPOINT_IMG-"quay.io/sustainable_computing_io/kepler_model_server:v0.7"}
```suggestion
export ENTRYPOINT_IMG=${ENTRYPOINT_IMG:-"quay.io/sustainable_computing_io/kepler_model_server:v0.7"}
```

2024-07-22 01:43 UTC, sthaha requested changes
Looks good overall, minor corrections though.

2024-07-24 08:39 UTC, sunya-ch commented
@SamYuan1990 Could you please rebase this PR and resolve the change request by @sthaha ?

2024-08-09 11:55 UTC, SamYuan1990 commented
updated. @sunya-ch , @sthaha

2024-08-09 14:26 UTC, sthaha approved these changes

2024-08-09 14:26 UTC, merged