Implement API Routes for any model output type
sustainable-computing-io/kepler-model-server pull request #43
Opened 2022-09-16 07:14 UTC by sunya-ch

This PR is related to #42.

In this PR, I complete implementation of the model server with API routes supporting for both json weight and archived model under the same format of request. 
 
```mermaid
flowchart LR;
   exporter -- model request in json --> model-server
   model-server -- model weight in json --> exporter
```
example response:
```json
{"cache_miss": 1, "cpu_cycles": 1, "cpu_instr": 1}
```

```mermaid
flowchart LR;
   exporter -- model request in json --> model-server
   model-server -- model weight per component in json --> exporter
```
example response:
```json 
{"core": {"cpu_cycles": 1, "cpu_instr": 1}, "dram": {"cache_miss": 1}}
```

```mermaid
flowchart LR;
   exporter -- unix.sock --> estimator -- model request in json --> model-server
   model-server -- archived folder of model in zip --> estimator
```
example response: 
```bash
tests/download/
└── AbsPower
    ├── KerasLR_Full.h5
    ├── core.h5
    ├── dram.h5
    ├── merge.pkl
    └── metadata.json
```
The main code is [model_server.py](https://github.com/sunya-ch/kepler-model-server/blob/train-4/server/model_server.py)

```python
```
Check example usage in [model_server_test.py](https://github.com/sunya-ch/kepler-model-server/blob/train-4/tests/model_server_test.py)

2022-09-16 15:11 UTC, KaiyiLiu1234 commented on server/train/pipeline.py
> +            os.remove(archived_file)
I do not think you need to remove the archived file. If it is saved you should be able to just call make_shutil and it should replace it. I will double check.

2022-09-16 15:13 UTC, KaiyiLiu1234 commented
Also if we are going to be archiving model, should we use SavedModel instead?

2022-09-16 15:15 UTC, KaiyiLiu1234 requested changes
I might be misunderstanding something in my previous comments, so feel free to correct me or provide further clarification.

2022-09-16 15:16 UTC, sunya-ch commented
> Also if we are going to be archiving model, should we use SavedModel instead?

Sure. You can save to any format in the pipeline train function. We just have to support that in the kepler-estimator.

2022-09-20 01:09 UTC, sunya-ch commented
Sorry for updating all changes at the same amend. 
I update the following changes.

- use previously-implemented `return_model_weights` to get weight json. However, combined core and dram to a single return for AbsComponentModelWeight type model.

> ```{"core": {"All_Weights": {"Numerical_Variables": {"cpu_cycles": {"weight": -2.709056854248047, "mean": 6571067392.0, "variance": 6.718171076850876e+18}, "cpu_instr": {"weight": 4.264798641204834, "mean": 3905655552.0, "variance": 4.049098354087428e+18}, "cpu_time": {"weight": 0.20845267176628113, "mean": 168149.25, "variance": 119128200.0}}, "Categorical_Variables": {"cpu_architecture": {"Sandy Bridge": {"weight": 0.5169816613197327}, "Ivy Bridge": {"weight": -0.10627192258834839}, "Haswell": {"weight": 0.10388034582138062}, "Broadwell": {"weight": 20.83293914794922}, "Sky Lake": {"weight": -0.32286643981933594}, "Cascade Lake": {"weight": -0.006997883319854736}, "Coffee Lake": {"weight": 0.5498881936073303}, "Alder Lake": {"weight": -0.18849200010299683}}}, "Bias_Weight": 21.37813377380371}}, "dram": {"All_Weights": {"Numerical_Variables": {"container_memory_working_set_bytes": {"weight": -14.61004638671875, "mean": 217088.0, "variance": 141381599232.0}, "cache_miss": {"weight": -10.457398414611816, "mean": 8926177.0, "variance": 21002180362240.0}}, "Categorical_Variables": {"cpu_architecture": {"Sandy Bridge": {"weight": 0.6605328917503357}, "Ivy Bridge": {"weight": 0.4871968626976013}, "Haswell": {"weight": -0.32830944657325745}, "Broadwell": {"weight": 28.224138259887695}, "Sky Lake": {"weight": -0.15247410535812378}, "Cascade Lake": {"weight": -0.019185900688171387}, "Coffee Lake": {"weight": 0.037583351135253906}, "Alder Lake": {"weight": -0.16830193996429443}}}, "Bias_Weight": 27.499914169311523}}} ```
   
   - similarly update to Sample in AbsModelWeight

- change from .h5 to SavedModel (tf format)
- remove unnecessary remove when archiving model

2022-09-21 17:32 UTC, KaiyiLiu1234 approved these changes
All required changes have been seen.

2022-09-22 15:03 UTC, merged